server:
  port: 4100

spring:
  application:
    name: ryuntech-su-cloud-admin-biz
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
    lettuce:
      shutdown-timeout: 0

  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://ryuntech-su-cloud-auth:4000/oauth/token
      user-authorization-uri: http://ryuntech-su-cloud-auth:4000/oauth/authorize
    resource:
      token-info-uri: http://ryuntech-su-cloud-auth:4000/oauth/check_token

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ryuntech-su-cloud-eureka:8761/eureka/

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.ryuntech.admin.api.entity


mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml

#mybaatis分页插件pagehelper设置
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true

# 打印sql
logging:
  level:
    com.ryuntech.admin.biz.mapper: DEBUG
